"""add fcm_token to user_profiles

Revision ID: 16b1062dbb6f
Revises: aa8be8c94413
Create Date: 2026-07-31 21:02:06.683400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '16b1062dbb6f'
down_revision: Union[str, Sequence[str], None] = 'aa8be8c94413'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_index(op.f('ix_solve_telemetry_user_id'), table_name='solve_telemetry')
    #op.drop_table('solve_telemetry')
    op.add_column('user_profiles', sa.Column('fcm_token', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'fcm_token')
    op.create_table('solve_telemetry',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('difficulty', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('solve_time_seconds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('attempts', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('snooze_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('solve_telemetry_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('solve_telemetry_pkey'))
    )
    op.create_index(op.f('ix_solve_telemetry_user_id'), 'solve_telemetry', ['user_id'], unique=False)
    # ### end Alembic commands ###
