"""Add snooze config to user_profiles

Revision ID: 3eb940a18b58
Revises: 
Create Date: 2026-07-19 16:44:39.762048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3eb940a18b58'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('snooze_limit', sa.Integer(), server_default='3', nullable=False))
    op.add_column('user_profiles', sa.Column('escalate_difficulty', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('user_profiles', sa.Column('time_penalty_enabled', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'time_penalty_enabled')
    op.drop_column('user_profiles', 'escalate_difficulty')
    op.drop_column('user_profiles', 'snooze_limit')
    # ### end Alembic commands ###
