"""initial_schema

Revision ID: aa8be8c94413
Revises: 
Create Date: 2026-07-23 20:35:26.864663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa8be8c94413'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_challenge_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('correct_answer', sa.String(length=500), nullable=False),
    sa.Column('time_taken_seconds', sa.Float(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('solved_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_challenge_history_user_id'), 'user_challenge_history', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('alarms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('alarm_time', sa.String(length=10), nullable=False),
    sa.Column('days_of_week', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('challenge_category', sa.String(length=50), nullable=False),
    sa.Column('difficulty_override', sa.String(length=20), nullable=True),
    sa.Column('snooze_limit', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alarms_user_id'), 'alarms', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('preferred_wake_time', sa.String(length=10), nullable=False),
    sa.Column('target_sleep_hours', sa.Float(), nullable=False),
    sa.Column('time_zone', sa.String(length=50), nullable=False),
    sa.Column('difficulty_preference', sa.String(length=20), nullable=False),
    sa.Column('productivity_goals', sa.String(length=500), nullable=True),
    sa.Column('snooze_limit', sa.Integer(), nullable=False),
    sa.Column('escalate_difficulty', sa.Boolean(), nullable=False),
    sa.Column('time_penalty_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_alarms_user_id'), table_name='alarms')
    op.drop_table('alarms')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_challenge_history_user_id'), table_name='user_challenge_history')
    op.drop_table('user_challenge_history')
    # ### end Alembic commands ###
